#!/bin/zsh

# https://github.com/mathiasbynens/dotfiles
# https://github.com/Stratus3D/dotfiles
# https://github.com/herrbischoff/awesome-macos-command-line#transparency

brew cask install iterm2

brew install zsh

# Install or update Home-brew
which -s brew
if [[ $? != 0 ]] ; then
    # Install Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew doctor
else
    brew update
fi


# Install Apple Office Applications
mas install 409203825  # Numbers
mas install 409183694  # Keynote
mas install 409201541  # Pages

# Install more recent versions of some macOS tools.
brew install vim --with-override-system-vi
brew install grep
brew install openssh

# Install other helpful utilities
brew install nmap
brew install ack
brew install tree

# Install m-cli - https://github.com/rgcr/m-cli                                               #
brew install m-cli

# Install openssl
brew install openssl

# Install Homebrew Cask
brew tap caskroom/cask

# Install Slack
brew cask install slack
open /Applications/Slack.app

# Install rocket.chat
brew cask install rocket-chat
open /Applications/Rocket.chat+.app

# Install signal
brew cask install signal

# Install Google Chrome
brew cask install google-chrome

# Install Firefox Developer Edition
brew cask install caskroom/versions/firefox-developer-edition

# Install Atom
brew cask install atom

# Install Spotify for music
brew cask install spotify

# Remove brew cruft
brew cleanup

# Remove cask cruft
brew cask cleanup

# Set hostname based on user input
echo "Machine name current settings: "
echo "Please set the computername, hostname, localhostname and netbiosname (Leave blank for no change): "
read -p "New Hostname: "newhostname
m hostname $newhostname
